module Champions.Ability where

class BlazeAbility a where blaze :: a
class ChlorophyllAbility a where chlorophyll :: a
class DampAbility a where damp :: a
class ElectricRodAbility a where electricRod :: a
class FlashFireAbility a where flashFire :: a
class GluttonyAbility a where gluttony :: a
class GutsAbility a where guts :: a
class HarvestAbility a where harvest :: a
class HydrationAbility a where hydration :: a
class ImmunityAbility a where immunity :: a
class InnerFocusAbility a where innerFocus :: a
class IntimidateAbility a where intimidate :: a
class JustifiedAbility a where justified :: a
class MagicGuardAbility a where magicGuard :: a
class MoldBreakerAbility a where moldBreaker :: a
class MoxieAbility a where moxie :: a
class MultiscaleAbility a where multiscale :: a
class NoGuardAbility a where noGuard :: a
class OvergrowAbility a where overgrow :: a
class PressureAbility a where pressure :: a
class RainDishAbility a where rainDish :: a
class RivalryAbility a where rivalry :: a
class RockHeadAbility a where rockHead :: a
class ShellArmorAbility a where shellArmor :: a
class SniperAbility a where sniper :: a
class SolarPowerAbility a where solarPower :: a
class StaticAbility a where static :: a
class SteadfastAbility a where steadfast :: a
class SwiftSwimAbility a where swiftSwim :: a
class SynchronizeAbility a where synchronize :: a
class ThickFatAbility a where thickFat :: a
class TorrentAbility a where torrent :: a
class UnnerveAbility a where unnerve :: a
class WaterAbsorbAbility a where waterAbsorb :: a
class ClearBodyAbility a where clearBody :: a
class LightMetalAbility a where lightMetal :: a
class SturdyAbility a where sturdy :: a
class HeavyMetalAbility a where heavyMetal :: a
class SandRushAbility a where sandRush :: a
class SandForceAbility a where sandForce :: a
class SuctionCupsAbility a where suctionCups :: a
class StormDrainAbility a where stormDrain :: a
class BattleArmorAbility a where battleArmor :: a
